apiVersion: apps/v1
kind: deployment
metadata:
  name: my-app
  namespace: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: helmcontainer.azurecr.io/dockerr:latest
          ports:
            - containerPort: 80
