apiVersion: v1
kind: Service
metadata:
  name: myapps
  namespace: theernamespace
spec:
  selector:
    app: myapps
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000